// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path = require("node:path");
const { defineConfig, env } = require("prisma/config");

module.exports = defineConfig({
  // The directory where your Prisma schema file lives (relative to this file)
  schema: "./prisma/schema.prisma",
  migrations: {
    path: "./prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
